version: "3.7"
services:
  db:
    container_name: hydra-db
    image: postgres:latest
    volumes:
      - "hydra_dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    ports:
      - "5420:5432"
    restart: always
volumes:
  hydra_dbdata: